name: Checksum watcher

on:
  schedule:
    # Runs every day at 11:00 UTC (12:00/13:00 in Norway depending on DST)
    - cron: "0 11 * * *"
  workflow_dispatch: {}

permissions:
  contents: write  # so we can push the updated log

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compute and compare checksum
        id: checksum
        run: |
          set -euo pipefail

          FILE_URL="https://cdn.jagex.com/Jagex%20Launcher%20Installer.exe"
          LOG_FILE="checksums.log"

          tmpfile=$(mktemp)
          curl -fsSL "$FILE_URL" -o "$tmpfile"

          NEW_SUM=$(sha256sum "$tmpfile" | awk '{print $1}')

          LAST_SUM=""
          if [ -f "$LOG_FILE" ]; then
            LAST_SUM=$(tail -n 1 "$LOG_FILE" | awk '{print $2}')
          fi

          if [ "$NEW_SUM" != "$LAST_SUM" ]; then
            NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            echo "$NOW $NEW_SUM" >> "$LOG_FILE"
            echo "changed=1" >> "$GITHUB_OUTPUT"
          else
            echo "changed=0" >> "$GITHUB_OUTPUT"
          fi

          echo "new_sum=$NEW_SUM" >> "$GITHUB_OUTPUT"
          echo "last_sum=${LAST_SUM:-}" >> "$GITHUB_OUTPUT"

      - name: Send Discord notification
        if: steps.checksum.outputs.changed == '1'
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          set -euo pipefail
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          NEW_SUM="${{ steps.checksum.outputs.new_sum }}"
          LAST_SUM="${{ steps.checksum.outputs.last_sum }}"

          # Build a basic Discord message
          CONTENT="✅ Checksum changed at $NOW\nNew: $NEW_SUM"
          if [ -n "$LAST_SUM" ]; then
            CONTENT="$CONTENT\nPrev: $LAST_SUM"
          fi

          curl -fsSL -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$CONTENT" '{content: $content}')" \
            "$DISCORD_WEBHOOK_URL"

      - name: Commit and push if changed
        if: steps.checksum.outputs.changed == '1'
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add checksums.log
          git commit -m "chore: checksum updated $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          git push
